workflows:
  ios-development:
    name: iOS Development Build
    instance_type: mac_mini_m1
    environment:
      node: latest
      xcode: latest
    scripts:
      - name: Install dependencies
        script: yarn install
      - name: Build iOS
        script: |
          npx expo prebuild --platform ios --clean
          cd ios
          pod install
          xcodebuild -workspace PlayTV4K.xcworkspace -scheme PlayTV4K -configuration Debug -sdk iphoneos
    artifacts:
      - ios/build/Debug-iphoneos/*.app
