workflows:
  ios-development:
    name: iOS Development Build
    instance_type: mac_mini_m1
    environment:
      node: latest
      xcode: latest
      ios_signing:
        distribution_type: development
        generate_new_certificate: true
      vars:
        BUNDLE_ID: "com.leoneltoh.playtv4k"
        XCODE_WORKSPACE: "PlayTV4K"
        XCODE_SCHEME: "PlayTV4K"
    scripts:
      - name: Install dependencies
        script: |
          yarn install
          npx expo prebuild --platform ios --clean
      - name: Install CocoaPods dependencies
        script: |
          cd ios && pod install
      - name: Set up code signing settings
        script: |
          xcode-project use-profiles
      - name: Build iOS
        script: |
          cd ios
          xcodebuild -workspace PlayTV4K.xcworkspace -scheme PlayTV4K -configuration Debug -sdk iphoneos -archivePath build/PlayTV4K.xcarchive archive
          xcodebuild -exportArchive -archivePath build/PlayTV4K.xcarchive -exportPath build/IPA -exportOptionsPlist exportOptions.plist
    artifacts:
      - ios/build/IPA/PlayTV4K.ipa
      - /tmp/xcodebuild_logs/*.log
