workflows:
  ios-development:
    name: iOS Development Build
    instance_type: mac_mini_m1
    environment:
      node: latest
      xcode: latest
      vars:
        EXPO_TOKEN: "y8MgUBG771013PAllzVGpq9_LmvzcubHVRSiNYQA"
    scripts:
      - name: Install dependencies
        script: |
          yarn install
          npm install -g eas-cli
      - name: Build iOS
        script: |
          eas build:configure
          eas build --platform ios --profile development --local
    artifacts:
      - build/**/*.ipa
      - /tmp/xcodebuild_logs/*.log
