workflows:
  ios-development:
    name: iOS Development Build
    max_build_duration: 30
    instance_type: mac_mini_m1
    environment:
      vars:
        EXPO_TOKEN: y8MgUBG771013PAllzVGpq9_LmvzcubHVRSiNYQA
      node: latest
    scripts:
      - name: Install dependencies
        script: |
          npm install
          npm install -g eas-cli
      - name: Configure EAS
        script: |
          cat > eas.json << 'EOL'
          {
            "cli": {
              "version": ">= 5.9.1",
              "requireCommit": false
            },
            "build": {
              "development": {
                "distribution": "internal",
                "ios": {
                  "resourceClass": "m-medium",
                  "buildConfiguration": "Debug"
                }
              }
            }
          }
          EOL
      - name: Build iOS
        script: |
          eas build --platform ios --profile development --non-interactive --local
    artifacts:
      - build/**/outputs/**/*.ipa
      - /tmp/xcodebuild_logs/*.log
    publishing:
      email:
        recipients:
          - graceafrica2@gmail.com
